### PR TITLE
Add Lithuanian localization

### PR DESCRIPTION
**Pull request by mantasio**
Translation to Lithuanian language for #1

### CODE REVIEW

**Review by arthurits — APPROVED** [review]

**Comment by arthurits** [comment]
Hi @mantasio!

Thanks so much for the Lithuanian translation. Please, find a snapshot down below.

image

**Comment by arthurits** [comment]
Just forgot to tell you that, should you be interested, there's another Lithuanian translation [needed here](https://github.com/arthurits/ErgoLux/issues/1), where many of the the strings are identical to the ones you've already translated.

**Comment by mantasio** [comment]
> Just forgot to tell you that, should you be interested, there's another Lithuanian translation [needed here](https://github.com/arthurits/ErgoLux/issues/1), where many of the the strings are identical to the ones you've already translated.
Done!

**Comment by arthurits** [comment]
> Done!

That's fantastic!
_Labai ačiū_

**Pull request merged**
