### PR TITLE
Translated to Bangla

### PR DESCRIPTION
**Pull request by sarequl**

### CODE REVIEW

**Comment by sarequl** [comment]
Hello @arthurits 
If there is any issue with the file, please let me know.
I will fix it.

Thank you

**Review by arthurits — APPROVED** [review]

**Comment by sarequl** [comment]
Please label it as hacktoberfest

**Review by arthurits — COMMENTED** [review]
Hi @sarequl 
I'm not conversant with Bangla, but looking at Microsof's documentation, it looks like the culture identification should be either [(bn-BD)](https://www.localeplanet.com/dotnet/bn-BD/index.html) or [(bn-IN)](https://www.localeplanet.com/dotnet/bn-IN/index.html).
I guess the translation is for bn-BD, but I'm not sure. Wouldn't you mind renaming the file accordingly so that I can merge your PR?

**Comment by sarequl** [comment]
sure,
Wait a moment

**Review by arthurits — APPROVED** [review]
Great! Thank you!

**Comment by sarequl** [comment]
Please check it now.

Also please label it as hacktoberfest.

Thank You <3

**Pull request merged**
