### PR TITLE
Add Dutch translation (nl-BE)

### PR DESCRIPTION
**Pull request by cvc04**
After translating [ErgoLux](https://github.com/arthurits/ErgoLux/pull/13), I have now also translated SignalAnalysis into Dutch. (#1)

### CODE REVIEW

**Review by arthurits — APPROVED** [review]

**Comment by arthurits** [comment]
Thanks so much @cvc04! That's a great addition to the software. Here's a screenshot:

image

**Comment by arthurits** [comment]
One more thing @cvc04:
I'm currently translating the context menu (see image below) both here and in ErgoLux. I would be very grateful if you wouldn't mind translating it for me. [It's just 9 strings...](https://github.com/arthurits/ErgoLux/blob/master/ErgoLux/controls/FormsPlotCulture.resx)

image

**Comment by cvc04** [comment]
Hi @arthurits 
I will translate it. You can expect it soon.

**Comment by arthurits** [comment]
> Hi @arthurits I will translate it. You can expect it soon.

Thanks so much! I really appreciate it.

**Pull request merged**
